import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Button from "../ui/Button/Button";

import Bottomnav from "../ui/Bottomnav/Bottomnav";
import TopNav from "../ui/Topnav/Topnav";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning
			>
				<div className='min-h-screen w-full flex items-center justify-center bg-gray-100'>
					<div className='w-[440px] h-[956px] bg-white shadow-lg relative overflow-hidden'>
						<TopNav />
						<main className='h-[calc(956px-120px)] overflow-y-auto'>
							{children}
						</main>
						<Bottomnav />
					</div>
				</div>
			</body>
		</html>
	);
}
